### ISSUE TITLE
[HELP] error message tidak tampil di preview

### ISSUE THREAD

**Issue by DhyasR** [alizaenazet/gamedoc-android#12]
## Detail problem
codenya ada di branch feature/issue-8/component-input-field

sudah aku coba-coba tapi error message tetap  tidak tampil di previewnya

## Other information
sudah aku coba buat rebuild project maupun edit-edit codenya tetapi messagenya tetap tidak mau keluar. di tampilan previewnya pada saat aku menggunakan code itu bagian input yang login rownya jadi lebih besar tetapi error messagenya tetap tidak keluar

**Comment by alizaenazet** [comment]
hellou, sepertinya memang kalau dilevel preview jetpack compose tidak memberikan kemampuan dalam tampilan seperti perubah tampilan akan interaksi, bisa dilakukan testing dengan melakukan build dan dijalankan pada emulator kamu. 

atau kamu bisa mencoba dengan cara membuat sebuah mutable state seperi pada solusi berikut : https://stackoverflow.com/questions/68573228/how-to-show-error-message-in-outlinedtextfield-in-jetpack-compose

**Comment by DhyasR** [comment]
> Owner

aku jadi pakai support text terus pas aku edit backround colornya pakai modifier kok nggak ngaruh ya?
