### ISSUE TITLE
[HELP] Border asli dari text fieldnya  tidak bisa di ubah warnanya

### ISSUE THREAD

**Issue by DhyasR** [alizaenazet/gamedoc-android#13]
## Detail problem
source dari branch feature/issue-8 [branch url](https://github.com/alizaenazet/gamedoc-android/blob/feature/issue-8/component-input-field/app/src/main/java/com/example/gamedoc/ui/components/InputField.kt)

border asli dari customeTextFieldnya tidak bisa dirubah warna. sudah aku coba edit di code materials tapi tetap tidak berpengaruh

## The problem assumptions
mungkin kesalahan ada di parameter warna atau di bodynya  di file materials

**Comment by alizaenazet** [comment]
faktor utama adalah ketika menggunakan `OutlinedTextField` dimana component tersebut tidak support custome border termasuk menggunakan _Gradient color_ pada border. 

1. ubah menjadi `TextField`
2. jangan gunakan `modifer` untuk mengatur background cukup gunakan `modifier` pada border agar dapat menggunakan _gradient color_ 
3. ubah beberapa paramter pada `CustomTextFieldValidation`
4. gunakan parameter `colors` pada component `TextField` seperti berikut 
```kotlin
colors = OutlinedTextFieldDefaults.colors(
                unfocusedContainerColor = backgroundColor,
                focusedContainerColor = backgroundColor,
                unfocusedBorderColor = Color.Transparent,
                errorBorderColor = Error,
                errorContainerColor = backgroundColor,
                errorLabelColor = Color.Transparent,
                focusedBorderColor = Color.Transparent,
            )
```
