### ISSUE TITLE
Nggak isa buat Button Dropdown

### ISSUE THREAD

**Issue by LouisSetyandaru** [alizaenazet/gamedoc-android#19]
## Detail problem

https://github.com/alizaenazet/gamedoc-android/blob/22c13a50ce7048cb5e53ad99d8b9b7c277bc7a07/app/src/main/java/com/example/gamedoc/ui/components/Button.kt#L212C4-L283C10

trs iki previene sg button terakhir

https://github.com/alizaenazet/gamedoc-android/blob/22c13a50ce7048cb5e53ad99d8b9b7c277bc7a07/app/src/main/java/com/example/gamedoc/ui/components/Button.kt#L287C3-L324C6

Jadi ini kan aku buat button trs ada button dengan fitur dropdown, laini aku coba buat pakai template buat component trs aku akalin pake code dari gpt jadi nya error, trs kalau aku lihat dari yutub itu bisa pakai tabukan pakai buttin tapi pakai collum, trs ada lagi kalau di totoruial yutub itu pake file xml, lah itu aku nggak tau giaman cara dapetin file xml e itu.

## The problem assumptions
ya karena untuk membuat sebuah menu dropdown tidak bisa menggunkan murni dari kotlin, melainkuan juga memrlukan file dari XML yang belum tau caranya bagaimana

## Other information
informasi tambahan

**Comment by DhyasR** [comment]
https://stackoverflow.com/questions/65507206/dropdown-list-on-button-click-compose

harusnya pakai itu bisa

**Comment by alizaenazet** [comment]
jetpack compose sudah menyediakan component untuk bikin dropdown button sendiri, bisa dicek pada link berikut : 

1. https://www.composables.com/material3/dropdownmenu
2. https://alexzh.com/jetpack-compose-dropdownmenu/

**Comment by alizaenazet** [comment]
sudah aku coba benerin divariant `dropdown` bisa kamu cek di [commitan aku dibranch tersebut](https://github.com/alizaenazet/gamedoc-android/pull/16/commits/2f8b7b35910d956add26a1b459039d0c0d978f05) .

coba kamu cek buttonya apakah sudah sesuai dan pastikan variant lainya yang sudah kamu garap bener dan sesuai juga jika memang telah dirasa sesuai bisa diclose issuenya
