### ISSUE TITLE
[HELP] error pas mau build project

### ISSUE THREAD

**Issue by DhyasR** [alizaenazet/gamedoc-android#7]
## Detail problem
`SDK location not found. Define a valid SDK location with an ANDROID_HOME environment variable or by setting the sdk.dir path in your project's local properties file at D:\Semester 3\1. Visual Programming\Project\gamedoc-android\local.properties`.

## The problem assumptions
aku udah coba cari di google disuruh buat kyk file baru cmn pas tak coba msh ga bisa, terus udah tak coba clean project terus tak build lagi tetep ndak bisa

## Other information
jadi pas mau tak lihat previewnya malah muncul error itu

**Comment by alizaenazet** [comment]
hii dhyas, dari error mu sepertinya disebabkan oleh IDE yang ga nemuin SDK ANDROID kamu, sehingga kamu sepertinya harus ubah sdk path secara ekspilist/manual. mungkin step-by-stepnya bakalan mirip tapi bisa kamu sesuaikan lagi kalau memang nda sesuai, pakai cara berikut :


1. Cari lokasi SDK Android kamu, beberapa sumber mengatakan by default ada pada path: `C:\Users\%USERNAME%\AppData\Local\Android\sdk` cek referensi [mengetahui path SDK Android](https://devicetests.com/where-is-the-android-sdk-folder)
2. lakukan cek dan sesuaikan pada file `local.properties`, file tersebut bersifat hidden sehingga untuk menampilkan file tersebut bisa lakukan `ls -la`. setelah itu masuk dan sesuaikan bila tidak sesuai dengan path android sdk kamu sebab kemungkinan dapat terjadi karena hasil clone/pull dari repostiory ku jalan di OS yang berbeda, dengan mengikuti langkah berikut : 

-   masuk ke direktori project androidnya
-  jalankan promp pada powersehell/bash `ls -la` dan akan keluar list folder dan list yang ada didirektori tersebut
- lalu masuk ke file `local.properties` dengna jalankan promp `nano local.properties` 
- maka akan mendapati isi file tersebut dan fokus pada baris 10/terakhir disana letak path SDK android mu seperti gambar berikut : 
<img width="629" alt="Screenshot 2023-12-16 at 18 19 15" src="https://github.com/alizaenazet/gamedoc-android/assets/96227680/15ffb04e-0232-434a-9a3c-751b3bad2b07">


3. cek dan Sesuaikan apabila tidak sesuai path pada android studio menuju lokasi path SDK yang sesuai, mungkin bisa ikut referensi [mengganti lokasi SDK secara meanual berikut](https://www.geeksforgeeks.org/different-ways-to-change-android-sdk-path-in-android-studio/)
